### ISSUE TITLE
lifting the limitation on the number of visible nodes

### ISSUE THREAD

**Issue by LSmantiz** [mapequation/network-navigator#17]
Dear mapequation authors,

first of all I want to thank you for great work and the accessability of your code and algorithms. The mapequation framework is really interesting and a powerful tool to analyse big networks. 

I am currently working on analyzing a big network on regional economic production network data and for that purpose it would be hugely beneficial to **see more than the 20 highest ranking nodes per module**. Is there any easy to reach solution lifting that limitation, e.g. through running your "network-navigator" app locally on my pc with a slight modification or are you even planning to relax that limitation on your web app?

Thank you for coming back at my question already in advance. Hope your team stays healthy in these demanding times.

All the best
Lasare

**Comment by antoneri** [comment]
Hi and thanks for your question and the kind words!

Yes, we plan to fix this, one way or another! The navigator was my first real React application so it suffers from some choices I did early on.

If you want to change this in a local instance, change the line 

```js
takeLargest(treeNode, 20);
```

in [NetworkNavigator.js](https://github.com/mapequation/network-navigator/blob/4e8ae5e3e4228e7add06946926c6a59d0282ec5c/src/components/NetworkNavigator.js#L119).

Please also comment out lines 9-23 in [index.js](https://github.com/mapequation/network-navigator/blob/c073d7ca9c937e40abf6969930926b3cc1d2d1f2/src/index.js#L9-L23) so we don't log any errors that might originate from your machine 😄 

Start your local instance by first running `npm i` followed by `npm start`.

As a side note, we are currently brainstorming the next network visualization tool based on the map equation which will be more suitable for producing paper ready figures.

Hope this helps!
Best,
Anton

**Comment by LSmantiz** [comment]
Dear Anton,

thanks for you fast response! Is there any fast way to run a local instance of the code that I can access on GitHub? I am not really used to code javascript /html or run websites at all. 

Big thanks already in advance.
All the best
Lasare

**Comment by antoneri** [comment]
No problem!

You need [Node.js](https://nodejs.org/en/download/). After installation, you should be able to run `npm -v` in a terminal or command prompt.

Download the source code and unzip it, then in the source directory, run the following:
```bash
npm i
npm start
```

This should, after a while, open a web browser with your local instance.

**Comment by antoneri** [comment]
Just checking in! Have you managed to get this to work?

If you have any specific requirements, I can help you set up a custom instance with another node-limit.

Let me know!

**Comment by LSmantiz** [comment]
Hi Anton,

sorry for not getting back at you. Thanks again for your help and guidance on setting up the local instance of the network navigator. 
I was able to start a local instance on my machine, however, I did not find the time to test it with the lifted node limitiation. As soon as I find the time, I will provide you with some feedback.

Kind regards!

**Comment by antoneri** [comment]
We've added node limits, and its live on [mapequation.org/navigator](https://www.mapequation.org/navigator/).

It's a bit of a hack, you have to zoom in and out for the settings to take effect. Hope this helps!
