### ISSUE TITLE
Displayed 'Exit flow' value for modules is entry flow

### ISSUE THREAD

**Issue by AlexChaloner** [mapequation/network-navigator#9]
Hi!

When using Infomap Online on a directed weighted graph and putting the .ftree output into Network Navigator, I find that the 'Exit flow' listed for a module is what the .ftree file has as its entry flow.

The graph I'm using:

[directed_graph.txt](https://github.com/mapequation/network-navigator/files/4281067/directed_graph.txt)

The .ftree file:
![exitflowInfomapOnline](https://user-images.githubusercontent.com/13849862/75774177-492d7b00-5d47-11ea-99f5-02c6ccd60f10.png)

The Network Navigator display:
![exitflowNavigator](https://user-images.githubusercontent.com/13849862/75774265-86920880-5d47-11ea-95c7-2bfa79bb202c.png)

**Comment by danieledler** [comment]
Hi, thanks for noticing the issue! We have an update on the way, we just need to do some checks and regenerate the example file with the latest Infomap.

**Comment by danieledler** [comment]
Hi @AlexChaloner, now we have updated the navigator to support the new ftree format that includes enterFlow. Please try again, maybe you have to `shift + reload` on the navigator to clear the old version from the cache.

**Comment by AlexChaloner** [comment]
It works perfectly! Thank you!
